name: Register Package
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to register or component to bump
        required: true
jobs:
  register:
    if: github.server_url == 'https://github.com'
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: julia-actions/RegisterAction@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
